### PR TITLE
Allow limiting x-scaling by a maximum value

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by PhilJay** [comment]
Short question concerning this:

```java
    public void setVisibleXRange(float minScaleX, float maxScaleX) {
        float maxScale = mDeltaX / minScaleX;
        float minScale = mDeltaX / maxScaleX;
        mViewPortHandler.setScaleXRange(minScaleX, maxScaleX);
     }
```

Shouldn't it be like this:


```java
    public void setVisibleXRange(float minScaleX, float maxScaleX) {
        float maxScale = mDeltaX / minScaleX;
        float minScale = mDeltaX / maxScaleX;
        mViewPortHandler.setScaleXRange(minScale, maxScale);
     }
```

?

**Comment by PhilJay** [comment]
If yes, I'll change it :-)

**Comment by danielgindi** [comment]
Yes the min/max got flipped... My bad!

**Comment by PhilJay** [comment]
Nah thats not what I meant, its about the parameter and the local variable

**Comment by danielgindi** [comment]
Oh yes

**Comment by danielgindi** [comment]
It happened to the other function as well. The culprits of copy-paste. Should have used Shift-F6...

**Pull request merged**
