### PR TITLE
Rtl legend & left-of-chart legend

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by PhilJay** [comment]
I wish I could merge this :-(
Unfortunately I myself changed about 200 lines on the LegendRenderer.java file and it would create a lot of conflicts.

**Comment by danielgindi** [comment]
Well then, commit your changes, I'll update the pull request!

‏בתאריך יום שלישי, 24 במרץ 2015, Philipp Jahoda <notifications@github.com>
כתב:

**Comment by PhilJay** [comment]
Thanks man! Changes commited and pushed.

**Comment by danielgindi** [comment]
Rebased!

**Pull request merged**
