### PR TITLE
Multiline labels

### PR DESCRIPTION
**Pull request by silva96**
To solve issue #1507 added multi line support via \n in the label string, also added LineSpacing integer as member of LimitLine in order to separate each line of the label as desired. Also cleaned up the code (cmd + shift + L ) thats why there are so many small changes)

screenshot_20160224-135019
screenshot_20160224-135602

### CODE REVIEW

**Comment by danielgindi** [comment]
There are better, built-in methods in Android to draw multiline text. 
There's actually a drawing function prepared for that in the Utils of MPAndroidCharts.

**Comment by silva96** [comment]
@danielgindi I want to collaborate, can you please tell me where do I find this drawing function? which built-in methods do you have in mind?

Best.

**Comment by rstuven** [comment]
@danielgindi @PhilJay Functions in Utils are more for line breaking given a fixed width (constrainedToSize.width). Perhaps this pull request's name should be more specific ("Forced multiline labels using \n"), but still is a needed feature when the target width is unknown.

**Comment by danielgindi** [comment]
Those functions support newlines as well, and use the OS's layout functions
to lay them out, no synthetic line heights etc.
Even when word wrapping is not desired- those functions should be used,
just without a width constraint.
בתאריך יום ו׳, 11 במרץ 2016 ב-16:43 מאת Ricardo Stuven <
notifications@github.com>:

**Comment by c-castillo** [comment]
+1 to this feature

**Comment by nkittsteiner** [comment]
+1. I need this feature.

**Comment by danielgindi** [comment]
Take a look at `drawMultilineText` in Utils.

**Comment by silva96** [comment]
I know, we proposed a new pull request using it. it's #1570 , take a look @danielgindi

**Pull request closed without merging**
