### PR TITLE
Fix piechart NPE

### PR DESCRIPTION
**Pull request by Johnson145**
This is a bugfix for #3470. It's based on #3207 and an alternative solution to #3603. Instead of just cancelling the current request, it will try to fix the missing object references. Furthermore, some similar but not identical errors are solved, too.

### CODE REVIEW

**Comment by msapps** [comment]
I am getting crash mentioned in [#3825](https://github.com/PhilJay/MPAndroidChart/issues/3825) for line chart. 
I checked your commits and i noticed that you have done some changes in LineChartRenderer as well. So i was wondering if those changes can be solution to my problem?
Can you help me in this one?

**Comment by Johnson145** [comment]
Actually, the changes in the LineChartRenderer have already been done in #3207. I just generalized that for the PieChartRenderer. However, to answer your actual question: Yes, I think you're problem can be solved by applying the same changes at the line(s) you're crash is occuring. I don't got the time to fix that one right now, but it should be straightforward for you to write a quick fix, if you have a look at the current changes. If you got any specific questions about it, feel free to ask. 

For the long run, it's probably the best solution to outsource the `getStrongDrawBitmap` method I wrote to a parent class or interface with default implementation to prevent having to handle this problem in each of the subclasses separately.

**Comment by msapps** [comment]
Ok.. will do the changes and let you know in case of any queries.. Thanks a lot for help mate!

**Comment by almic** [comment]
Merged 3207, closing.

**Pull request closed without merging**
