### PR TITLE
Fix for chart not being drawn if visible portion starts with a NaN

### PR DESCRIPTION
**Pull request by noberasco**

### CODE REVIEW

**Comment by JKorsten** [comment]
Is this also possible for the barchart? Now the when I have NaN values my data isn't positioned correctly

**Comment by noberasco** [comment]
resynced with current master, plus added additional fix for chart fill

**Comment by JKorsten** [comment]
Why isn't this in the current release yet?

**Comment by almic** [comment]
@noberasco the pull request by semirke already does this

**Comment by biosignalssolutions** [comment]
I can't plot NaN value for LineChart on android API29. (samsung A41)   using set.getEntryForIndex(i).setY(NaN);
With android API23 (BQ Aquaris E5) works without any change at code.

Any solution/comment, please.
Thanks.

**Pull request closed without merging**
