### PR TITLE
Performance + Crash fix (#1892) (#1895)

### PR DESCRIPTION
**Pull request by tonypatino-monoclesociety**
This pull request contains --
1) All the allocation optimizations to the library, including unit tests for new classes.  (#1892)
2) Bitmap buffering of drawn circles in LineChartRenderer (#1892)
3) Crash fix and stress test for (#1895)

Note-- This change set will require approving a pull request in the MPAndroidChart-Realm project, to account for a new abstract method to retrieve the number of circle colors.  https://github.com/PhilJay/MPAndroidChart-Realm/pull/1

### CODE REVIEW

**Comment by danielgindi** [comment]
Is this actually *tested* and proved to be worth it?
As it can easily get out of hand - if someone forgets to recycle a size or a point, or returns too early etc. Also the overhead of taking an FSize from the pool and returning it - might sometimes be more costly than just allocating - or preallocating a single instance private to the class.

**Comment by danielgindi** [comment]
Also all of that overhead just for the sake of pooling long-running objects like a formatter in the example, or an ZoomJob - that's just nonsense.

**Comment by tonypatino-monoclesociety** [comment]
[comparison.zip](https://github.com/PhilJay/MPAndroidChart/files/404338/comparison.zip)

The two allocation charts show the app running at its default 500 allocation example.  Format string caching is a significant part of the memory allocation difference in these readings.  

The master branch incurred one GC run before the end of the 500 entries, and was near to incurring a second.  At 5000 entries, master incurred garbage collection about 15 times.  

The merged feature branch allocates a fraction of the memory.  Even at 5000 entries, it was not remotely close to incurring garbage collection.

The results from gfx info indicate that after all the changes the worst case screen rendering times improve between 25%-40%.  The rendering time per frame is much more consistent with these updates.  GC hiccups account for some of this difference.  The rest is accounted for by caching the the drawn circles inside the LineChartRenderer, which ends up far less expensive computationally than re-drawing all the circles during each onDraw() call.


As it stands, the end user neglecting to recycle an FSize or MPPointF doesn't result in issues beyond the original issue of wasted memory.

**Comment by danielgindi** [comment]
How is caching the string formatter giving you any benefit? It does not make any sense. These are set once - and reused as a variable. There's no reason to cache them.

Well if the user neglecting to recycle an FSize or a point is not an issue - then it's logical to consider it not being an issue if not taken from the pool at all.

It seems like there's some good work here on the object pools, but in some cases it's just an overkill...

**Comment by tonypatino-monoclesociety** [comment]
Caching the formatted string results prevents the application from calling
the mFormat.format() method repeatedly, to re-create formatted strings that
it has done the work to format once already.  The original code even
specifically calls DefaultAxisValueFormatter.getFormattedValue out as a
hotspot in the comments, indicating that memory allocation related to
.format() in the java codebase was a known issue

// avoid memory allocations here (for performance)

Unfortunately mFormat.format() is very allocation-hungry all on its own,
and the previous implementation would re-create format strings for values
that it had already once created.  The caching eliminates all excessive
allocations for strings that have already been generated, reducing garbage
substantially.

As for failing to recycle the points not being an issue in terms of correct
functioning of the application, the recycling exists as a way to improve
performance where it's needed, such as in animated graphs, or graphs that
update values over time.  It's there to allow users the option to be
economical.  The comparisons in the zip file are striking, and the option
is a good one to have.  The FSize and PointF savings in memory allocation
is larger still than the large savings from caching the strings, given the
thousands of instantiations that occur even with a small dataset.



*Tony Patino *| Development Lead
tonypatino@monoclesociety.com
206.718.8363 <+206-718-8363> (mobile)

**Pull request merged**
