### PR TITLE
Readme: add notice about Proguard

### PR DESCRIPTION
**Pull request by Evisceration**
* When using proguard and NOT whitelisting MPAndroidChart, some functionality
    will break like animate methods.

Change-Id: If329842301eb41f7f713c1148b5ca364917e3d7a
Signed-off-by: Alexander Martinz <eviscerationls@gmail.com>

### CODE REVIEW

**Comment by Evisceration** [comment]
This was something old i had lying around in my local branches.

I just noticed that you have updated the animation code since i had to whitelist it at proguard.

Will recheck if this still applies :)

**Comment by Evisceration** [comment]
Yes, unfortunately it still applies.

W/PropertyValuesHolder﹕ Method setPhaseX() with type float not found on target class class com.github.mikephil.charting.animation.ChartAnimator

just whitelisting the ChartAnimator works as well.
-keep class com.github.mikephil.charting.animation.ChartAnimator { *; }

**Comment by mesropd** [comment]
Right fix, and here is the explanation why it breaks )
https://github.com/PhilJay/MPAndroidChart/issues/348

**Comment by Evisceration** [comment]
alright, as i see this was noticed before already (sorry for not going through all the closed issues :))

**Pull request merged**
