### PR TITLE
[Feature] set gradient color for bar chart (Edited)

### PR DESCRIPTION
**Pull request by oatrice**
image

-set gradient color for bar chart

How to use.

``` java
int startColor = ContextCompat.getColor(this, android.R.color.black);
int endColor = ContextCompat.getColor(this, android.R.color.white);
set1.setGradientColor(startColor, endColor);
```

U can use this feature by add dependency of my fork this repository.

  -  Add the following to your project level `build.gradle`:

```gradle
allprojects {
	repositories {
		maven { url "https://jitpack.io" }
	}
}
```
  -  Add this to your app `build.gradle`:
 
```gradle
dependencies {
	implementation 'com.github.oatrice:MPAndroidChart:3.0.4'
}
```

### CODE REVIEW

**Comment by tabish075** [comment]
@oatrice i tried adding gradient to horizontal bar it didnt work it shows a solid sky blue color instead of gradient

**Comment by marwan-aziz** [comment]
@tabish075 Did you manage to add gradient to horizontal bar in the end, Im facing same problem.

**Comment by oatrice** [comment]
Oh, sorry for a horizontal case because I did not apply this case in my working.
I'll add this feature as soon as possible.

**Comment by oatrice** [comment]
@tabish075 @marwan-aziz 
I already create PR for gradient color for Horizontal BarChart.

You can see how to use or other detail for this feature.
https://github.com/PhilJay/MPAndroidChart/pull/4769
Screenshot_1577410549

**Pull request closed without merging**
