### PR TITLE
Selected point text on YAxis, dashed grid lines and option for showing YAxis grid lines when isShowOnlyMinMaxEnabled is true

### PR DESCRIPTION
**Pull request by mesropd**
Here are 4 features that I implemented
1 . Option to draw selected point text on the Y axis
```
        MyMarkerView mv = new MyMarkerView(getActivity(), R.layout.custom_marker_view);
        mv.setAxisTextColor(Color.parseColor("#a61f67"));
        mv.setAxisTextSize(20);
        mv.setAxisDependency(YAxis.AxisDependency.RIGHT);
        mv.setDrawAxisText(true);
        chart.setMarkerView(mv);

        public class MyMarkerView extends MarkerView {
        ......
        // callbacks everytime the MarkerView is redrawn, can be used to update the
        // content (user-interface)
        @Override
        public void refreshContent(Entry e, int dataSetIndex) {
            if (e instanceof CandleEntry) {
                CandleEntry ce = (CandleEntry) e;
                //tvContent.setText("" + Utils.formatNumber(ce.getHigh(), 0, true));
            } else {
                //tvContent.setText("" + Utils.formatNumber(e.getVal(), 0, true));
            }
            setAxisText(String.format("%.2f", e.getVal()));
        }
```
2 . Dash grid lines for YAxis and XAxis
3 . Show grid lines for YAxis when isShowOnlyMinMaxEnabled is true, because there are cases, when we want to show only min/max, but also want to keep grid lines
```
        YAxis rightAxis = chart.getAxisRight();
        rightAxis.setTextColor(Color.parseColor("#737888"));
        rightAxis.setTextSize(20);
        rightAxis.setStartAtZero(false);
        rightAxis.setShowOnlyMinMax(true);
        rightAxis.setShowGridLinesIfOnlyMinMax(true);
        rightAxis.enableGridDashedLine(4.0f, 4.0f, 0);
        rightAxis.setGridLineWidth(1.0f);
```
4 . Add option to continue scrolling with friction after touch up (https://www.youtube.com/watch?v=9Z8UH8mB5Qg)
```
        chart.setFlingFrictionEnabled(true);
        chart.setFlingFrictionCoef(0.8f);
```

Here is the screenshot
b0270828-d2d0-11e4-8bdf-402eb02542db

### CODE REVIEW

**Comment by danielgindi** [comment]
Could you please clean the pull request a little, and maybe if it's not too much trouble - separate to different pull request for each feature?

That would make that a million times easier to review the code...

Thanks :-)

**Comment by mesropd** [comment]
At first it was a small pull reqest :) I must create separate branch for each reqest, right? or there is an easy way.

**Comment by danielgindi** [comment]
Yeah it's a separate branch...
>
>

**Comment by mesropd** [comment]
This was my first pull request in git hub, at first I didn't know to do so, but then I implemented an another feature in separate branch, but don't know how to separate these 4 features, Is there a way to separate these commits into separate branches, or too late now?

**Comment by mesropd** [comment]
Did hard reset, will push every feature in the separate branch

**Comment by danielgindi** [comment]
Great thanks! :)
>
>

**Pull request closed without merging**
