### PR TITLE
Added gradle dependency information

### PR DESCRIPTION
**Pull request by jitpack**
So that MPAndroidChart can be easily added to gradle Android projects

### CODE REVIEW

**Comment by PhilJay** [comment]
Thank you.

I have a short question:
Everytime I create a new release of this library, will it automatically be available in the public repository for everyone to use as a dependency? Or does that require any extra work except from updating the "Readme" file with the latest version?

**Comment by jitpack** [comment]
Hi,
the nice thing is that no extra work is required. As soon as someone requests that new version JitPack will build it. Of course, if you like, you can make that first request to check that it works but generally if `gradle install` succeeds locally then it should on JitPack.

Maven information is correct. 

One thing to consider is a badge since it will show the latest release:
[Release](https://jitpack.io/#PhilJay/MPAndroidChart)

**Comment by PhilJay** [comment]
Awesome, thank you!

**Comment by PhilJay** [comment]
Sorry to bother you again, do you have any idea why the v2.0.1 causes build errors?

See here: https://jitpack.io/#PhilJay/MPAndroidChart

**Pull request merged**
