### PR TITLE
Labels at specific positions for x and y axis

### PR DESCRIPTION
**Pull request by philippeauriach**
This PR allows users to tell the graph which labels should be drawn.
Example : 
```
leftAxis.setShowSpecificLabelPositions(true);
leftAxis.setSpecificLabelPositions(new float[]{0, 10, 20, 50, 100, 300});
```
With this labels will only be drawn for values 0, 10, 20, 50, 100, 300, whatever the size of the graph. This is especially useful for "fixed" graphs, when for example you want to display start and end dates, with only a few between those. 

I added an example, see SpecificXLabelsLineChartActivity

### CODE REVIEW

**Comment by sanogueralorenzo** [comment]
Hello thanks for your PR and PhilJay for this awesome lib.

Will this be useful for horizontal scrollable graphs? I have a use case where I need to be able to display in the X axis 5 years in months just displaying the first 12 at the beginning (visibleXRangeMaximum = 12) and I only want to display 4 labels (xAxis.setLabelCount = 4).

This is working perfectly but setLabelCount tries to split the labels as equally as possible.

Is there any way I would be able to specify so only the first 3 months of every year are drawn?

Thank you in advance.

**Comment by philippeauriach** [comment]
It could work yes, if you know how much years you are drawing (with my PR you must tell the graph exactly which labels should be drawn). For example : 
`leftAxis.setSpecificLabelPositions(new float[]{0, 1, 2, 3, 12, 13, 14, 15});`
would work (if your months are 0 based) for the first two years.

Otherwise, if today you are able to display every month, but only wants the first 4 of each year, I suggest creating a custom value formatter and returning an empty string for the months you dont want to display.

**Comment by rohangoqii** [comment]
@philippeauriach  Super job! Just what I was looking for.  

@PhilJay Any plans on accepting this PR any time soon? This looks like a good value addition to the library.

**Comment by rohangoqii** [comment]
@philippeauriach  Hey Phillipe. I am trying to have a graph where all my labels are plotted( like months in a year or days in a week) but I only have data for a few points i.e (number of entries < number of labels). 

How do I modify this to correctly plot my entries. Right now with the current implementation, only a certain number of labels are being plotted i.e up to the corresponding entry in the graph with the same x value. So if my x label position max is 50, but the max x position value of an entry is 20, I can only see my labels up to 20. 

I would like all labels to be plotted so I can scroll the entire length of labels(with a few entries)

**Comment by philippeauriach** [comment]
@rohangoqii my PR does not modify how the axis is drawn, just which labels at which positions.
I suggest looking at the axis doc, you can customize max and min values using `setAxisMaximum(float max)` and `setAxisMinimum(float min)`, it should help you achieve what you want.

**Comment by rohangoqii** [comment]
That's exactly what I did!! Thanks @philippeauriach

**Comment by Rohfosho** [comment]
Why hasn't this been merged in yet? @PhilJay

**Comment by bakua** [comment]
For anyone in the need of this behavior before the branch is merged. This is this PR's code all bundled into one `XAxisRenderer` so it can be injected into chart via `setXAxisRenderer()` method.

```
internal class SpecificPositionLabelsXAxisRenderer(
    viewPortHandler: ViewPortHandler,
    xAxis: XAxis,
    trans: Transformer,
    private val specificLabelPositions: FloatArray
) : XAxisRenderer(viewPortHandler, xAxis, trans) {

    override fun drawLabels(c: Canvas, pos: Float, anchor: MPPointF) {
        val labelRotationAngleDegrees = mXAxis.labelRotationAngle
        val positions = FloatArray(specificLabelPositions.size * 2)
        for (i in 0 until positions.size step 2) {
            positions[i] = specificLabelPositions[i / 2]
        }

        mTrans.pointValuesToPixel(positions)

        for (i in 0 until positions.size step 2) {
            var x = positions[i]
            if (mViewPortHandler.isInBoundsX(x)) {
                val label = mXAxis.valueFormatter.getFormattedValue(specificLabelPositions[i / 2], mXAxis)
                if (mXAxis.isAvoidFirstLastClippingEnabled) {
                    // avoid clipping of the last
                    if (i == mXAxis.mEntryCount - 1 && mXAxis.mEntryCount > 1) {
                        val width = Utils.calcTextWidth(mAxisLabelPaint, label)
                        if (width > mViewPortHandler.offsetRight() * 2 && x + width > mViewPortHandler.chartWidth)
                            x -= width / 2
                        // avoid clipping of the first
                    } else if (i == 0) {
                        val width = Utils.calcTextWidth(mAxisLabelPaint, label)
                        x += width / 2
                    }
                }

                drawLabel(c, label, x, pos, anchor, labelRotationAngleDegrees)
            }
        }
    }
}
```

**Comment by TiiXel** [comment]
Thanks to @bakua I found an alternative approach that does not override`drawLabels` and thus has the following advantages:

- allows label rotations without cropping
- allows label count to be dynamically adjusted to the chart size

```
fun BarLineChartBase<*>.setSpecificPositionLabels(labels: Set<Float>) {
    setXAxisRenderer(
        SpecificPositionLabelsXAxisRenderer(
            viewPortHandler,
            xAxis,
            getTransformer(axisLeft.axisDependency),
            labels.toFloatArray()
        )
    )
}

private class SpecificPositionLabelsXAxisRenderer(
    viewPortHandler: ViewPortHandler,
    xAxis: XAxis,
    trans: Transformer,
    private val specificLabelPositions: FloatArray,
    private val adjustLabelCountToChartWidth: Boolean
) : XAxisRenderer(viewPortHandler, xAxis, trans) {

    override fun computeAxisValues(min: Float, max: Float) {
        
        mAxis.mEntryCount = specificLabelPositions.size
        mAxis.mEntries = specificLabelPositions
        mAxis.setCenterAxisLabels(false)
        
        computeSize()
        
        if (adjustLabelCountToChartWidth) {
            val width = mXAxis.mLabelRotatedWidth
            
            while (width * mAxis.mEntryCount > mViewPortHandler.chartWidth / 2f) {
                mAxis.mEntries = mAxis.mEntries.filterIndexed { index, fl -> index % 2 == 0 }.toFloatArray()
                mAxis.mEntryCount = mAxis.mEntries.size
            }
        }
    }
}
```

**Comment by almic** [comment]
Could you please create a new pull request for this, as the file structure has changed. This looks fine, except I recommend that instead of creating a brand new example activity, please find one existing activity and show it off there without changing the chart too much. Thank you!

**Comment by androidovshchik** [comment]
Another example for x axis as dates  
Thanks to @remiberthoz 
```
fun BarLineChartBase<*>.setDateLabels() {
    setXAxisRenderer(
        DateLabelsXAxisRenderer(viewPortHandler, xAxis, getTransformer(axisLeft.axisDependency))
    )
}

private class DateLabelsXAxisRenderer(
    viewPortHandler: ViewPortHandler,
    xAxis: XAxis,
    transformer: Transformer
) : XAxisRenderer(viewPortHandler, xAxis, transformer) {

    override fun computeAxisValues(min: Float, max: Float) {
        with(mAxis) {
            val count = (mAxisRange / DAY).toInt()
            if (mEntries.size != count) {
                mEntries = FloatArray((mAxisRange / DAY).toInt()) {
                    mAxisMinimum + (it + 0.5f) * DAY
                }
            } else {
                mEntries.indices.forEach {
                    mEntries[it] = mAxisMinimum + (it + 0.5f) * DAY
                }
            }
            mEntryCount = mEntries.size
            computeSize()
        }
    }
}
```

**Pull request closed without merging**
