### PR TITLE
Fix #1536, #1608 (IndexOutOfBoundsException in drawCubicFill())

### LINKED ISSUE #1536: IndexOutOfBoundsException in drawCubicFill() since 2.2.3
I'm getting an IndexOutOfBoundsException in 2.2.3 - see the stack trace blow. This seems to be related to the following pull request:

https://github.com/PhilJay/MPAndroidChart/pull/1516

```
03-02 17:44:31.767 5948-5948/net.techet.netanalyzer.an E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: net.techet.netanalyzer.an, PID: 5948
                                                                         java.lang.IndexOutOfBoundsException: Invalid index 52, size is 45
                                                                             at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                             at java.util.ArrayList.get(ArrayList.java:308)
                                                                             at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:250)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubicFill(LineChartRenderer.java:260)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubic(LineChartRenderer.java:232)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:125)
                                                                             at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:108)
                                                                             at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:249)
                                                                             at android.view.View.draw(View.java:16184)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1369)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.draw(View.java:16187)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                             at android.view.View.draw(View.java:15954)
                                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                             at android.view.View.draw(View.java:16187)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                         	at android.view.Choreographer$FrameDisplayEventReceiver
```

### PR DESCRIPTION
**Pull request by dexterbg**

### CODE REVIEW

**Comment by danielgindi** [comment]
Nope. This is incorrect. #1536 existed before this change.

**Comment by dexterbg** [comment]
Daniel, Phil, would you mind posting the correct solution? My patch fixes the bug for my application, and I'm about to release that, so I'd rather know if / why that's wrong.

**Comment by danielgindi** [comment]
Your patch does not pass correct values so bugs could appear when zooming in + scrolling + animating.
We don't have a solution yet- because we cannot reproduce the issue

**Comment by dexterbg** [comment]
You can't reproduce the issue because it's already fixed in the master branch, only 2.2.3 release version is affected.

Sorry for not checking this before submitting my fix & thanks for stopping my invalid submission.

**Pull request closed without merging**
