### PR TITLE
YAxis: add missing setDrawBottomYLabelEntry method

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**
## PR Checklist:
- [-] I have tested this extensively and it does not break any existing behavior.

## PR Description

add missing setDrawBottomYLabelEntry method in YAxis

this prevent can prevent bottom y axis value from overlapping with left x axis value

It is an important and useful method

### CODE REVIEW

**Comment by ljubisa987** [comment]
@PhilJay Could you please consider merging this PR, thanks!

**Comment by veratapiap** [comment]
Please, i need this method, thanks!

**Comment by ryanzzff** [comment]
Duplicate of #4785

**Comment by SubhrajyotiSen** [comment]
@ryanzzff Please check dates of both the PRs

**Comment by ryanzzff** [comment]
> @ryanzzff Please check dates of both the PRs

Sorry, my intention is just want to mark both PRs are duplicated, and just want any of them to be merged.

**Comment by SubhrajyotiSen** [comment]
> > @ryanzzff Please check dates of both the PRs
> 
> Sorry, my intention is just want to mark both PRs are duplicated, and just want any of them to be merged.

At the current stat of the repo, I doubt any of the PRs will be merged. Best bet would be to make a fork and apply the changes

**Comment by SubhrajyotiSen** [comment]
Merged this at https://github.com/SubhrajyotiSen/MPAndroidChart which will be an updated fork

**Pull request closed without merging**
