### PR TITLE
Added support for the Legend entries to be displayed in row/column

### PR DESCRIPTION
**Pull request by nmac143**
To use, call LegendName.setOrientation(Legend.LegendOrientation.VERTICAL/HORIZONTAL);
Added example to combined chart...                  
screenshot_20150812-165806

*May still be buggy so I would double check before pushing these changes to the main branch.

### CODE REVIEW

**Comment by danielgindi** [comment]
In order to be able to see what's going on here - you MUST REBASE  this PR. Clean it up, and squash it.

**Comment by nmac143** [comment]
@danielgindi Sorry I am new to github. I wasn't quite sure if more or less commits would be helpful.

**Comment by PhilJay** [comment]
I'm no longer sure if I should merge this?
Is this working or will it mess everything up?
And what feature exactly got added here?

**Comment by nmac143** [comment]
Looking back on this I probably should not have requested a pull request. If I have the time I will fix the problems and push it in a more concise package.

**Comment by PhilJay** [comment]
Allright, thank you!

**Pull request closed without merging**
