### PR TITLE
Avoid that the last label entry in the x-labels "clip" off the edge of the screen #3819

### PR DESCRIPTION
**Pull request by longup**
Modified the “drawLabels” methon in class XAxisRenderer, i should be i/2 in line 210, so the last label can be handled correctly.

### CODE REVIEW

**Comment by longup** [comment]
Please review this commit and merge to fix this bug, thank you.

**Comment by AliGolmirzaei** [comment]
I have the same issue and I think this is the fix. please review it. thank you

**Comment by almic** [comment]
This bug is not caused by the XAxisRenderer. The value you changed, `i` to `i / 2` is checking if the current drawn label is the last label, and if so, it correctly shifts it back `width / 2`, since the label is already centered and only half clips off.

Please use `xAxis.setAvoidFirstLastClipping(true)`. If that still doesn't fix the problem, you can simply increase the visible X range with `xAxis.axisMaximum(float)`, just add `0.5f` or similar to the last X value.

**Comment by longup** [comment]
Hello, I have use xAxis.setAvoidFirstLastClipping(true) and increase the visible X range with xAxis.axisMaximum(float), but it crash, like this:
`float lastValue = lineChart.getXAxis().getAxisMaximum();
        lineChart.getXAxis().setAxisMaximum(lastValue + 1.0f);`

And I have try a lot of values, but it doesn't work. Only if I changed  the value  i to i / 2, it worked fine.

Thank you，please review it.

**Pull request closed without merging**
