### PR TITLE
Support for negative values in stacked vertical bar chart

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by PhilJay** [comment]
This seems like not that many changes, I can't believe that works already. :-)
Did you base this on my code? I thought I was further away from a stable solution^^

**Comment by danielgindi** [comment]
Yes it's based on your code - it's the same for vertical bars as for
horizontal bars. It worked for me on iOS :-)

The only thing that's different in your calculations for horizontal bars
are left/right/top/bottom flipping, but receiving data with the same
meaning. This is way you can take the exact same code...

**Comment by PhilJay** [comment]
Sounds great!
Did you check out the age distribution charts that are now possible with this? Looks kind of fancy :-)
But there are still issues concerning highlighting unfortunately...

**Comment by danielgindi** [comment]
Yes it's very useful! And it actually surprised me how easy it was to allow
this, by changing only a few lines of code to support the negative values..
Yes highlighting is a mess, we'll need to take the negativeSum +
positiveSum as the size of the bar, starting from -negativeSum, so it
doesn't sound too tricky to me...

**Comment by PhilJay** [comment]
please tell me that I did not just push the images stuff to master again

**Comment by danielgindi** [comment]
No you did not... It's a separate branch now :-)

**Comment by PhilJay** [comment]
I got kind of scared because I saw `XValue`. So this was in the master branch all along?

**Comment by danielgindi** [comment]
Oh dammit

**Comment by danielgindi** [comment]
It's possible that your local fork was not in sync with the history change
and you re-pushed all that stuff

**Comment by danielgindi** [comment]
Try to do:
git reset --hard 43e9c26

And the
git push --force

After that you'll be on a clean slate, and just re-merge

**Comment by PhilJay** [comment]
I think I didn't checkout the clean origin master, instead I pulled which was bad since I still had the pie-stuff at master locally :-)

You mean re-merge the PR you just made?

**Comment by danielgindi** [comment]
Yeah I re-opened that PR

**Comment by PhilJay** [comment]
done

**Comment by danielgindi** [comment]
Now if you're working on experimental branch, you might want to reset that
too, with the exact same code, while you're on experimental.
Or just re-clone the repo to be sure :-)

**Pull request merged**
