### PR TITLE
Auto scale y axis

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by PhilJay** [comment]
Can you in short explain what that feature does?

**Comment by danielgindi** [comment]
Yes :-)
When you change the viewport to show only a subset of the data (for example by scaling on the x axis) - it causes the y axis to scale to that subset of data.

You can see an explanation here: https://github.com/danielgindi/ios-charts/issues/89

**Comment by danielgindi** [comment]
This feature was proposed by @AlBirdie which works with financial charts, and is required by him. So this opens up more possibilities for those working with financial charts.

**Comment by Bhupendra-tbox** [comment]
Hi Daniel, Can we get max & min value after change autoScaleMinMaxEnabled feature?

**Comment by jlo1** [comment]
@danielgindi  curious if you have any thoughts/fixes for this issue here: https://github.com/PhilJay/MPAndroidChart/issues/3374

Thanks!

**Pull request merged**
