### PR TITLE
[Feature] set gradient color for bar chart

### PR DESCRIPTION
**Pull request by oatrice**
-set gradient color for bar chart
-Add javadoc for getter/setter method
-add kotlin

How to use.

``` java
int startColor = ContextCompat.getColor(this, android.R.color.black);
int endColor = ContextCompat.getColor(this, android.R.color.white);
set1.setGradientColor(startColor, endColor);
```

### CODE REVIEW

**Comment by VyMajoris** [comment]
Can we have this, please?

**Comment by oatrice** [comment]
test

**Comment by VyMajoris** [comment]
@oatrice Nice, thank you.

**Comment by almic** [comment]
Adding support for gradients is definitely on the to-do list, however this pull request has way too many extra changes. If you could please create a **new pull request**, preferably with only ONE commit, that only adds the ability to set a second color for bar chart entries, which the renderer then uses that second color to draw a gradient on the bar. I will gladly merge it!

**Comment by oatrice** [comment]
@almic  Thank you for your commenting. I new pull request again at this #3999

**Pull request closed without merging**
