### PR TITLE
Scatter - support for shape holes, new X shape

### PR DESCRIPTION
**Pull request by danielgindi**
This is for the next version, let it sink in for a few days :-)

### CODE REVIEW

**Comment by PhilJay** [comment]
Version 2.2.2? or 2.2.3?

**Comment by danielgindi** [comment]
2.2.2 :-) We've ended up making the latest realm fixes in 2.2.2 and not needing 2.2.3, so it should be 2.2.2

**Comment by danielgindi** [comment]
I think this can be merged now

**Comment by PhilJay** [comment]
Quick question: What does a hole in a cross look like? :-)

**Comment by danielgindi** [comment]
No idea. That's why crosses do not have holes ;-)
If you find out- let me know! lol

**Comment by PhilJay** [comment]
Ok :-D

**Comment by PhilJay** [comment]
Offtopic: Should I merge the branch where I removet the startatzero property?
Or do you think this is not a  good idea?

**Comment by danielgindi** [comment]
If I read the code correctly - it is backwards compatible, adjusting the mixAxis accordingly right?
In this case I don't see any problem, except maybe that it is not that clear to people that they can use NaN values in floats... It would work better in Swift, where values can be nullable so its clear that the minimum is optional.

**Pull request merged**
