### PR TITLE
Fix null pointer exception in draw markers

### PR DESCRIPTION
**Pull request by JacobJust**
Fixed this issue: https://github.com/PhilJay/MPAndroidChart/issues/2917

We get crashes from our customers, but we are not able to reproduce the issues. Added a null check, for the variable set, which can be null.

### CODE REVIEW

**Comment by cubizh** [comment]
This seems to be a nobrainer PR.
This issue happens to me when I remove the line where the marker is on at the moment.
I managed to get around this bug by .setDrawMarkers(false); on chart creation and only doing .setDrawMarkers(true); inside onValueSelected()

**Comment by RaviUmraliya** [comment]
"This seems to be a nobrainer PR.
This issue happens to me when I remove the line where the marker is on at the moment.
I managed to get around this bug by .setDrawMarkers(false); on chart creation and only doing .setDrawMarkers(true); inside onValueSelected()"

@cubizh  ya it's work

**Comment by alejouribesanchez** [comment]
> This seems to be a nobrainer PR.
> This issue happens to me when I remove the line where the marker is on at the moment.
> I managed to get around this bug by .setDrawMarkers(false); on chart creation and only doing .setDrawMarkers(true); inside onValueSelected()

This also works for me

**Comment by Poojamalik810** [comment]
I am using MP chart library for behaving it like the real time graph to draw line graph in a real time way.


But the above solutions not working for me.  Infact, after setting .setDrawMarkers(false); on chart creation and only doing .setDrawMarkers(true); inside onValueSelected()
 I am not able to get any value when chart any point is clicked. That is, my marker donot give any value when clicked and it is crashing throwing this error.

I am continuously getting crash and getting this error.

**Kindly help as soon as possible how to handle this error**.

If anyone has used real time graph in android application. Kindly help me out.

**Comment by Poojamalik810** [comment]
Help guys facing this issue from past many days as soon as possible

**Pull request closed without merging**
